### ISSUE TITLE
Vencord creator is f@ggot

### ISSUE THREAD

**Issue by lynrayy** [MrDiamondDog/noUglyIconsTheme#12]
The fucker "vending.machine" banned me for trolling, although, damn, there was no trolling! I was outraged that vencord did not provide the ability to install plugins out of the box. This idiot just banned me! Fucked up! He dont even tried to solve the conflict!

Fucking raged

**Comment by lynrayy** [comment]
Уёбище ебаное

**Comment by MrDiamondDog** [comment]
they banned you for being a troll. me and others were trying to help you but you just complained constantly for no reason AND ban evaded AND now you're harassing anyone you can just because you got banned. if you are really that pressed about how hard it is to use custom plugins, then don't use them.
